# Generated by Django 3.0.8 on 2020-08-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200807_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
