# Generated by Django 3.0.8 on 2020-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200807_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='torder',
            field=models.IntegerField(default=1),
        ),
    ]
