# Generated by Django 3.0.8 on 2020-08-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odetails', to='api.Order'),
        ),
    ]
