# Generated by Django 3.0.8 on 2020-09-08 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200811_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='order',
        ),
        migrations.AddField(
            model_name='inventory',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Employee'),
        ),
    ]
