# Generated by Django 3.0.8 on 2020-09-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200908_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='typemov',
        ),
    ]
