# Generated by Django 3.0.8 on 2020-09-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_inventory_typemov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='detailinventory',
            name='total',
        ),
    ]
