# Generated by Django 3.0.8 on 2020-09-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_detailmov_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
