# Generated by Django 3.0.8 on 2020-09-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_detailmanifest_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
