# Generated by Django 3.0.8 on 2020-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_movement_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tpayment',
            field=models.IntegerField(default=1),
        ),
    ]
