# Generated by Django 3.0.8 on 2020-09-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_tpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmanifest',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omanifestdetails', to='api.Manifest'),
        ),
    ]
