# Generated by Django 3.0.8 on 2020-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200915_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minstock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
