# Generated by Django 3.0.8 on 2020-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivery2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hour_delivery',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
