# Generated by Django 3.0.8 on 2020-09-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200916_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minstockclient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
