# Generated by Django 3.0.8 on 2020-11-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_movement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Order'),
        ),
    ]
