# Generated by Django 3.0.8 on 2020-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_manifest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
