# Generated by Django 3.0.8 on 2021-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20201123_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
