# Generated by Django 3.0.8 on 2021-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.TextField(blank=True, null=True),
        ),
    ]
