# Generated by Django 3.0.8 on 2021-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='seriales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
