# Generated by Django 3.0.8 on 2021-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_detailorder_seriales'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinventory',
            name='seriales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailmanifest',
            name='seriales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
