# Generated by Django 3.0.8 on 2021-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210426_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='series2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
