# Generated by Django 3.0.8 on 2021-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_product_series2'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmov',
            name='seriales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
